title = "Application Config"

[logger]
level = "info"

[app]
separate_business_class_output = false
output_to_excel = true
use_excel_config = true

[input]
input_file = "gg_fare_input.xlsx"
input_sheets = [
  "input",
  "cabin_mapping",
  "season_mapping",
  "fare_combination",
  "config",
]

[output]
  [output.all]
    output_file = "output.xlsx"
  [output.business]
    output_file = "business_output.xlsx"
  [output.non-business]
    output_file = "output.xlsx"